CREATE TABLE `todo` (
    `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
    `user_id` bigint UNSIGNED NOT NULL,
    `titlle` varchar(255) NOT NULL,
    `description` varchar(255) NOT NULL DEFAULT '',
    `start_dateTime` datetime NOT NULL,
    `end_dateTime` datetime NOT NULL,
    `is_finished` boolean DEFAULT false,
    `is_star` boolean DEFAULT false,
    `priority` varchar(32) DEFAULT NULL,
    `location` varchar(255) DEFAULT NULL,
    `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted_at` datetime DEFAULT NULL,
    PRIMARY KEY (`id`),
    KEY `idx_user_id` (`user_id`),
    KEY `idx_created_at` (`created_at`),
    KEY `idx_updated_at` (`updated_at`),
    KEY `idx_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
